# Generated by Django 3.1.5 on 2021-09-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('para', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_date',
            field=models.DateTimeField(null=True),
        ),
    ]
